# Generated by Django 4.0.4 on 2022-04-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rota',
            options={},
        ),
        migrations.RemoveField(
            model_name='rota',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='rota',
            name='atualizacao',
        ),
        migrations.RemoveField(
            model_name='rota',
            name='criacao',
        ),
        migrations.AlterField(
            model_name='rota',
            name='distance',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
        migrations.AlterField(
            model_name='rota',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rota',
            name='target',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Local',
        ),
    ]
