# Generated by Django 4.0.4 on 2022-04-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0002_alter_rota_options_remove_rota_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='rota',
            name='distance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rota',
            name='source',
            field=models.CharField(choices=[('A', 'Exemplo A'), ('B', 'Exemplo B'), ('C', 'Exemplo C'), ('D', 'Exemplo D'), ('E', 'Exemplo E')], max_length=1),
        ),
    ]
